export const ActionType = {
  GETALL__PRODUCT: "GETALL__PRODUCT",
  FILTER__PRODUCT: "FILTER__PRODUCT",
  FAV__PRODUCT: "FAV__PRODUCT",
  REMOVE__FAV: "REMOVE__FAV",
  ADD__CARD: "ADD__CARD",
  REMOVE__CARD: "REMOVE__CARD",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  TOTAL: "TOTAL",
  SELECT__MODE: "SELECT__MODE",
  SELECT__COLOR: "SELECT__COLOR",
};
